apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: sample
spec:
 selector:
   matchLabels:
      app: django-project
 replicas: 2
 strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

 template:
  metadata:
    labels:
     app: django-project
  spec:
    containers:
    - name: django-project
      image: nginx
      imagePullPolicy: Always
      ports:
      - containerPort: 80

