kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: demoservice
  namespace: sample
spec:
  ports:
  -  port: 80  
     protocol: TCP
     targetPort: 80 
     nodePort: 31782 # Pods port
  selector:
    app: django-project
                           # Apply this service to any pods which has the specific label
  type: NodePort                       # Specifies the service type i.e ClusterIP or NodePort

