apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab
type: Opaque
data:
  runner-registration-token: Z2xydC1iMndWR0g4YWRCN1BkLXZHYWh4Yw== # need to leave as an empty string for compatibility reasons
    #  runner-token: "REDACTED"

